package constant

const (
	NOT_AUTHORIZED       = "NOT_AUTHORIZED"
	NO_CREDENTIAL        = "NO_CREDENTIAL"
	SERVICE_CREATE_ISSEU = "SERVICE_CREATE_ISSEU"
	BAD_REQUEST          = "BAD_REQUEST"
	SERVICE_PARSE        = "SERVICE_PARSE"
	SERVICE_RETURN       = "SERVICE_RETURN"
	SERVICE_VAliDATE     = "SERVICE_VAliDATE"
	FIELD_DESCRIPTION    = "FIELD_DESCRIPTION"
	FIELD_URI            = "FIELD_URI"
)
